name: Update Package Version

on:
    release:
        types: [released]

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Update package.json
              run: |
                  node ./scripts/updateVersion.js ${{ github.event.release.tag_name }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Commit changes
              run: |
                  git add .
                  git commit -m "Update version to ${{ github.event.release.tag_name }} for ${{ github.ref }}"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
