name: Test yml

on:
    push:
        branches:
            - 'main'
    workflow_dispatch: # 手动触发
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
                type: choice
                options:
                    - info
                    - warning
                    - debug
            tags:
                description: 'Test scenario tags'
                required: false
                type: boolean
            environment:
                description: 'Environment to run tests against'
                type: environment
                required: true

jobs:
    update:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Update package.json
              run: |
                  node ./scripts/updateVersion.js ${{ github.event.release.tag_name }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Commit changes
              run: |
                  git config --global user.email "251115151@qq.com"
                  git config --global user.name "fansonly"
                  git add .
                  git commit -m "Update version to ${{ github.event.release.tag_name }} for ${{ github.ref }}"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
